kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vvdevdsdatalake-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: vvdevdsdatalake-pv
  storageClassName: azureblob-fuse-csi-standard
