apiVersion: v1
kind: PersistentVolume
metadata:
  name: vvdevdsdatalake-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-csi-standard
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: vvdevdsdatalake
    volumeAttributes:
      containerName: storage
    nodeStageSecretRef:
      name: vvdevdsdatalake-storage
      namespace: spark
